fail_fast: true
repos:
-   repo: local
    hooks:
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
      language_version: python3.6
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      language_version: python3.6
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
